name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v4.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
      - name: Zip Project
        run: zip -r ${GITHUB_REPOSITORY#*/}.zip .
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Copying repository zipfile to AWS S3
        run: |
          aws s3 cp ${GITHUB_REPOSITORY#*/}.zip s3://${{ secrets.AWS_S3_ARCHIVE_BUCKET }}/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}.zip